### PR TITLE
Latest OS-HPXML

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

Pulls in:
- [x] https://github.com/NREL/OpenStudio-HPXML/pull/1685
  - Add `geometry_unit_height_above_grade=auto` under Geometry Building Type RECS in options_lookup
  - Created https://github.com/NREL/resstock/issues/1303 as a future TODO
- [x] https://github.com/NREL/OpenStudio-HPXML/pull/1775
  - We can now remove the "Other" plug load calculations block from ResStockArguments that was using the regression equations
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1690
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1822
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1824
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1823
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1833
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1827
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1817
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1834
- [x] https://github.com/NREL/OpenStudio-HPXML/pull/1829
  - Using ResStockArguments, populate new `schedules_unavailable_period_xxx` arguments using old `schedules_vacancy_periods`, `schedules_power_outage_periods`, and `schedules_power_outage_periods_window_natvent_availability` arguments that are assigned in the lookup
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1836
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1837
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1838
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1825
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1707
- [x] https://github.com/NREL/OpenStudio-HPXML/pull/1826
  - Introduce `window_interior_shading_type`, `window_exterior_shading_type`, and `window_insect_screens` to the lookup but set them all to `auto`
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1842
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1843
- [ ] https://github.com/NREL/OpenStudio-HPXML/pull/1844

Checked means that something in resstock was changed or updated as a result of pulling in.

**_Other_ plug loads change for MH:**
image

**_Television_ plug loads change for all building types:**
image

**Some occupant-driven end uses (pool, spa, range/oven, well pump, gas grill/fireplace/lighting, etc) increase:**
image
image
image
image

## Checklist

Not all may apply:

- [ ] ~Tests (and test files) have been updated~
- [x] Documentation has been updated
  - [ ] ~If related to resstock-estimation, checklist includes [data dictionary](https://github.com/NREL/resstock/tree/develop/resources/data/dictionary), [source report](https://github.com/NREL/resstock/tree/develop/project_national/resources/source_report.csv), [options saturation](https://github.com/NREL/resstock/tree/develop/project_national/resources/options_saturations.csv), [options_lookup](https://github.com/NREL/resstock/blob/develop/resources/options_lookup.tsv).~
- [x] Add to the [changelog_dev.rst file](https://github.com/NREL/resstock/tree/develop/docs/read_the_docs/source/changelog/changelog_dev.rst)
- [x] `openstudio tasks.rb update_measures` has been run
- [x] No unexpected regression test changes on CI (checked comparison artifacts)

### CODE REVIEW

**Comment by joseph-robertson** [comment]
> > * Add `geometry_unit_height_above_grade=auto` under Geometry Building Type RECS in options_lookup
> 
> You might consider setting a value in ResStockArguments for apartment units based on the type/size of MF building and where the unit is located (lower, middle, or upper story).

Probably more straightfoward for upper vs middle story (where there could be multiple middle stories)?

**Comment by joseph-robertson** [comment]
> > > * Add `geometry_unit_height_above_grade=auto` under Geometry Building Type RECS in options_lookup
> > 
> > 
> > You might consider setting a value in ResStockArguments for apartment units based on the type/size of MF building and where the unit is located (lower, middle, or upper story).
> 
> Probably more straightfoward for upper vs middle story (where there could be multiple middle stories)?

First step might be to try different heights (e.g., 0, 8, ..., 24) to understand how much impact this has. Then could think about using average values for different building heights.

**Comment by joseph-robertson** [comment]
In ResStock, when do we use the _unadjusted_ number of bedrooms?

**Comment by joseph-robertson** [comment]
> In ResStock, when do we use the _unadjusted_ number of bedrooms?

Setting the number of bedrooms is not only a [required HPXML field](https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#hpxml-building-construction), but it is an [input for ACCA Manual J design loads](https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#id179).

**Comment by shorowit** [comment]
> * Introduce `window_interior_shading_type`, `window_exterior_shading_type`, and `window_insect_screens` to the lookup but set them all to `auto`

You might consider using them instead of summer/winter coefficients. They interact with window type (SHGC), whereas the coefficients have no interaction. Though it will be a definite change from what ResStock is doing today.

**Pull request merged**
