### PR TITLE
Correct number of sink DHW draw clusters per occupant

### LINKED ISSUE #569: Fix number of sink clusters per occupant
Currently 6000 sink clusters per occupant is assumed: https://github.com/NREL/resstock/blob/49f5e9b94a96a73f53797fd8fc02b11bbe76438c/resources/measures/HPXMLtoOpenStudio/resources/schedules/schedule_config.yml#L44

My rough calculations show that ~2600 would be a better assumption.

N_BR | BAHSP Sink GPD H+C Household | N_occ_sf | BAHSP Sink GPD H+C per occupant | Annual sink clusters per hh | Annual sink clusters per occ
-- | -- | -- | -- | -- | --
0 | 12.5 | 0.87 | 14.4 | 3443 | 3957
1 | 16.66 | 1.46 | 11.4 | 4588 | 3143
2 | 20.82 | 2.05 | 10.2 | 5734 | 2797
3 | 24.98 | 2.64 | 9.5 | 6879 | 2606
4 | 29.14 | 3.23 | 9.0 | 8025 | 2485
5 | 33.3 | 3.82 | 8.7 | 9171 | 2401
  |   |   |   |   |  
Nat'l avg number of occs| 24.2 | 2.53 | 9.6 | 6657 | 2631

[sink_cluster_check_ew.xlsx](https://github.com/NREL/resstock/files/6272934/sink_cluster_check_ew.xlsx)

@afontani How do you want to go about merging this in w.r.t. EULP calibration?
@rajeee fyi

### PR DESCRIPTION
**Pull request by ejhw**
Resolves #569 

## Pull Request Description

Correct number of sink DHW draw clusters per occupant. Changing to 2631 would be the easy fix. ~~Alternatively, we could use an equation for sink clusters per occupant:~~

~~# Based on 6885 clusters for 25 gpd, from Building America DHW Event Schedule Generator~~
~~sink clusters per occupant = (1941.8 * N_occ + 1753.1)/N_occ~~

*Edit: see pseudocode at https://github.com/NREL/resstock/issues/569 for the equations we want to implement.*

If we wanted to use sink usage multipliers, we could even scale the number of clusters by the multiplier to get more usage diversity.

## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [ ] All rake tasks have been run, and pass
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [ ] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [ ] All tests are passing
- [ ] The [changelog](https://github.com/NREL/resstock/blob/master/CHANGELOG.md) has been updated appropriately
- [ ] This branch is up-to-date with develop

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Review by rajeee — APPROVED** [review]
Looks good to me.

**Comment by afontani** [comment]
@ejhw, @rajeee: Is this good to go? Or we waiting on the equations to be implemented in the PR description?

**Comment by ejhw** [comment]
@afontani I wrote some pseudocode at the issue: https://github.com/NREL/resstock/issues/569. I was hoping that @rajeee could implement it.

**Comment by rajeee** [comment]
@afontani and @ejhw Oh, sorry. I missed that. I can implement that equation.

**Comment by joseph-robertson** [comment]
@rajeee So this can be closed since #579 was merged?

**Comment by rajeee** [comment]
> @rajeee So this can be closed since #579 was merged?

Yep. 

Addressed in: https://github.com/NREL/resstock/pull/579

**Pull request closed without merging**
