### PR TITLE
Fix unmet hours

### PR DESCRIPTION
**Pull request by shorowit**
Resolves #[issue number here].

## Pull Request Description

Excludes reported unmet hours for A) no heating and/or cooling equipment and B) finished basements.

## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [ ] All rake tasks have been run, and pass
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [ ] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [ ] All tests are passing
- [ ] The [changelog](https://github.com/NREL/resstock/blob/develop/CHANGELOG.md) has been updated appropriately
- [ ] This branch is up-to-date with develop

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by shorowit** [comment]
This is now an apples-to-apples comparison. 

Before:

image

After:

image

**Comment by joseph-robertson** [comment]
Can you remind me why we exclude finished basements?

**Comment by shorowit** [comment]
So that you don't double count hours where both above-grade finished space and finished basement aren't meeting the load.

**Comment by joseph-robertson** [comment]
So hours not met will be zero when there is no heating/cooling equipment? Is this misleading?

**Comment by shorowit** [comment]
This output is typically used to determine if you have undersized HVAC systems that can't keep up with the load. It's more confusing to have very large values simply because you have no HVAC system; that makes it hard to identify large values where you actually _have_ an HVAC system, which are the datapoints of particular interest.

**Review by joseph-robertson — APPROVED** [review]

**Pull request merged**
