### PR TITLE
Also mention run_analysis.rb

### PR DESCRIPTION
**Pull request by ejhw**
## Pull Request Description

[description here]

## Checklist

Not all may apply:

- [ ] Tests (and test files) have been updated
- [ ] Documentation has been updated
- [ ] Changelog has been updated
- [ ] `openstudio tasks.rb update_measures` has been run
- [ ] No unexpected integration/regression test changes

### CODE REVIEW

**Review by joseph-robertson — COMMENTED** [review]
Seems like our objective here is to make the options for running ResStock more apparent (i.e., on the first page of the docs)? If so, do we want to highlight these two paragraphs perhaps in a "Note" (blue box)?

**Comment by ejhw** [comment]
> Seems like our objective here is to make the options for running ResStock more apparent (i.e., on the first page of the docs)? If so, do we want to highlight these two paragraphs perhaps in a "Note" (blue box)?

I  like the blue note box idea.

**Comment by joseph-robertson** [comment]
image

**Comment by joseph-robertson** [comment]
> Thanks @joseph-robertson . I added another note on that page and changed a link from a hyperlink to a ref. Can you confirm my reference is working?

It looks like this. Probably not what you were going for:
image

**Comment by joseph-robertson** [comment]
How about this?
image

where

image

**Review by joseph-robertson — APPROVED** [review]

**Comment by joseph-robertson** [comment]
Landing page:
image

Installation:
image

Run the Project:
image

**Pull request merged**
