### PR TITLE
Replace room-ac performance curves by Cutler curves

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

Backports:
* https://github.com/NREL/OpenStudio-HPXML/pull/698
* https://github.com/NREL/OpenStudio-HPXML/pull/701
* https://github.com/NREL/OpenStudio-HPXML/pull/764

`example_single_family_detached_TMY.osw` with ResidentialHVACRoomAirConditioner:
* `develop`: 
image
* `room-ac-curves`:
image

## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [ ] All rake tasks have been run, and pass
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [ ] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [ ] All tests are passing
- [ ] The [changelog](https://github.com/NREL/resstock/blob/develop/CHANGELOG.md) has been updated appropriately
- [ ] This branch is up-to-date with develop

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by joseph-robertson** [comment]
@ejhw @afontani @aspeake

This is the first item from https://trello.com/c/0lwzEytE/76-port-os-hpxml-fixes-over-to-develop. So for example do we want to go ahead and merge this? Or do we first want to compare each of these items to resstock-hpxml?

**Comment by ejhw** [comment]
@joseph-robertson I don't see any benefit to comparing to resstock-hpxml before we merge. Probably want to do a separate EULP run for this change. cc @afontani

**Comment by joseph-robertson** [comment]
There's a bit more to do on this one.

**Review by shorowit — APPROVED** [review]
The CI only shows simulation results changing for samples w/ room ACs, and they change in the expected way. I also compared the performance curves in a single ResStock IDF to an OS-HPXML IDF and they match. This looks good to me.

**Comment by joseph-robertson** [comment]
We should go ahead and merge this into develop, and then @afontani can do his EULP runs.

**Pull request merged**
