### PR TITLE
Don't read the whole buildstock.csv file

### PR DESCRIPTION
**Pull request by rajeee**
Resolves high memory consumption issue that was causing the eagle and aws runs to crash.

## Pull Request Description

Since the buildstock.csv was being read in whole into memory, it was consuming a lot of memory (approx 5.5 GB when reading a 550K buildstock.csv). This was in turn causing OOM issues on eagle nodes and making them run super slow. This fix scans the buildstock.csv and retrieves the row for a given building_id without loading everything into memory.

This PR basically does undo of [this](https://github.com/NREL/resstock/pull/640/files) PR but keeps the speed up for the test_samples.rb.
## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [ ] All rake tasks have been run, and pass
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [ ] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [ ] All tests are passing
- [ ] The [changelog](https://github.com/NREL/resstock/blob/develop/CHANGELOG.md) has been updated appropriately
- [ ] This branch is up-to-date with develop

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Review by shorowit — APPROVED** [review]
CI confirms that there's no runtime regression to test_samples.rb. This looks good. Nice job tracking it down and fixing it. Sorry that my previous PR had an unintended consequence. 😬

**Comment by rajeee** [comment]
@shorowit Thanks! 
Do you know what is the reason for the diff in results_output.csv ?https://github.com/NREL/resstock/pull/701/commits/75772cf29460d0765cf1c8d5227f56bcbf9c1e92

**Comment by shorowit** [comment]
Every PR relative to develop generates _slightly_ different results for a few homes. It's nothing specific to your changes and will go away when ResStock switches to HPXML. So it's nothing to worry about.

**Comment by rajeee** [comment]
@shorowit Thanks. And when/how do the statuses get updated?

**Comment by shorowit** [comment]
Ah, it's not going to update again because there was an automated commit to the PR (which doesn't trigger the CI tests again). I'll go ahead and merge.

**Pull request merged**
