### PR TITLE
Report supplemental electric heating

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

Break "supplemental electric heating" out of "electric heating".

This is important for heat pump analysis.

## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [ ] All rake tasks have been run, and pass
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [ ] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [ ] All tests are passing (green) on circleci
- [ ] The [changelog](https://github.com/NREL/OpenStudio-BuildStock/blob/master/CHANGELOG.md) has been updated appropriately
- [ ] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Review by ejhw — APPROVED** [review]
Thanks Joe! Looks good to me. CC @rajeee @afontani  for awareness in case we need to update EZVIZ or EULP notebooks. We should probably wait to merge until after our 11/30 milestone.

**Comment by ejhw** [comment]
@joseph-robertson @afontani I think now would be a good time to merge this since we're through the milestone runs. cc @whiphi92

**Comment by joseph-robertson** [comment]
@afontani did you end up testing this branch in any runs?

**Comment by afontani** [comment]
@joseph-robertson: I have not tested this branch yet. I see that there is a new field being outputted. Do any models in project_national use this new feature? It not, how would we use it?

**Comment by afontani** [comment]
@joseph-robertson: I have not tested this branch yet. I see that there is a new field being outputted. Do any models in project_national use this new feature? It not, how would we use it?

**Comment by afontani** [comment]
@joseph-robertson: I have not tested this branch yet. I see that there is a new field being outputted. Do any models in project_national use this new feature? If not, how would we use it?

**Comment by whiphi92** [comment]
@afontani the new field helps analysis of the effects of night setback and constant temperature set points. It will aid analysis of the effects of upgrading electric strip heaters with ASHP with electric strip back up.

**Pull request merged**
