### PR TITLE
Update comments for n/a with more explanation

### PR DESCRIPTION
**Pull request by ejhw**
## Pull Request Description

Companion to https://github.com/NREL/resstock-estimation/pull/183

## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [ ] All rake tasks have been run, and pass
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [ ] No unexpected regression test changes
- [ ] All tests are passing
- [ ] The [changelog](https://github.com/NREL/resstock/blob/develop/CHANGELOG.md) has been updated appropriately
- [ ] This branch is up-to-date with develop

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by ejhw** [comment]
@joseph-robertson Do you know why this shows that checks haven't completed? Here it looks like they have: https://github.com/NREL/resstock/actions/runs/1664541865 Also could you please review this PR when you have a chance?

**Comment by joseph-robertson** [comment]
> @joseph-robertson Do you know why this shows that checks haven't completed? Here it looks like they have: https://github.com/NREL/resstock/actions/runs/1664541865 Also could you please review this PR when you have a chance?

The checks show waiting because of the "Latest results" commit that is made from GitHub Actions itself. That commit does not undergo the same GitHub Actions tasks (build, compare-results, etc.) as when you make a direct commit.

**Review by joseph-robertson — APPROVED** [review]

**Comment by ejhw** [comment]
> The checks show waiting because of the "Latest results" commit that is made from GitHub Actions itself. That commit does not undergo the same GitHub Actions tasks (build, compare-results, etc.) as when you make a direct commit.

Thanks. How do I get it to unblock the merge though?

**Comment by joseph-robertson** [comment]
> > The checks show waiting because of the "Latest results" commit that is made from GitHub Actions itself. That commit does not undergo the same GitHub Actions tasks (build, compare-results, etc.) as when you make a direct commit.
> 
> Thanks. How do I get it to unblock the merge though?

As admin, you should still be able to merge. Are you not able to?

**Pull request merged**
