### PR TITLE
Hide output directories

### PR DESCRIPTION
**Pull request by nmerket**
## Pull Request Description

Hide the output directories for the test projects.

## Checklist

Not all may apply:

- [ ] Tests (and test files) have been updated
- [ ] Documentation has been updated
- [ ] Changelog has been updated
- [ ] `openstudio tasks.rb update_measures` has been run
- [ ] No unexpected regression test changes on CI (checked comparison artifacts)

### CODE REVIEW

**Comment by nmerket** [comment]
I did it when I added integration testing to buildstockbatch. It was creating output directories that were showing up as untracked changes. I saw what looked like it should have been those directories in the .gitignore and "fixed" them so they would actually ignore those files.

**Review by joseph-robertson — APPROVED** [review]

**Comment by nmerket** [comment]
@joseph-robertson What made the difference in this working now?

**Comment by joseph-robertson** [comment]
> @joseph-robertson What made the difference in this working now?

Merging in develop. But I don't know why it was failing before. [Here](https://github.com/NREL/resstock/actions/runs/3380618123/workflow) is the "Workflow file" when I click on the link for the failed actions. It doesn't even show the job step (i.e., integration-tests: Upload output files) that fails in the run...

**Comment by nmerket** [comment]
Alright. Well if we're good, we're good. :shipit:

**Pull request merged**
