### PR TITLE
Update Hot Water Fixtures tsv

### PR DESCRIPTION
**Pull request by lixiliu**
## Pull Request Description

Resolves: https://github.com/NREL/resstock/issues/1236
Companion ResStock-Estimation PR: https://github.com/NREL/resstock-estimation/pull/420

Mean-shifted distribution from 0.8 to 1.0
Specifically, the previous distribution is specified as a lognormal distribution with a transformed mean of 0.8 and a stdev 0.2.
New distribution is tabulated directly from mean-shifted input data (with mean=1.0 and a stdev ~ 0.236).
image

## Checklist

Not all may apply:

- [ ] Tests (and test files) have been updated
- [x] Documentation has been updated
  - [x] If related to resstock-estimation, checklist includes [data dictionary](https://github.com/NREL/resstock/tree/develop/resources/data/dictionary), [source report](https://github.com/NREL/resstock/tree/develop/project_national/resources/source_report.csv), [options saturation](https://github.com/NREL/resstock/tree/develop/project_national/resources/options_saturations.csv), [options_lookup](https://github.com/NREL/resstock/blob/develop/resources/options_lookup.tsv).
- [x] Add to the [changelog_dev.rst file](https://github.com/NREL/resstock/tree/develop/docs/read_the_docs/source/changelog/changelog_dev.rst)
- [ ] `openstudio tasks.rb update_measures` has been run
- [ ] No unexpected regression test changes on CI (checked comparison artifacts)

### CODE REVIEW

**Review by jmaguire1 — COMMENTED** [review]
Looks good to me. I definitely still want to test this with a ResStock run, but I also need to pull in a branch of the latest OS-HPXML to do this. I'll talk to Joe about if we can do the run with these as open PRs.

**Comment by jmaguire1** [comment]
Results with these updates:

image

This is MUCH better than we used to be. If we wanted to get to exactly 1.0, I think we could shift the mean in this distribution to be 3% lower (the average across all usage levels in this 30k sample, which should be big enough to be representative). That said, I'd be fine with this as is, compared to the huge boost in hot water use we were doing. I suspect this will have a pretty minimal effect on energy use, maybe on the edges of some HPWH cases you'll end up with more element usage, but overall being slightly higher than 100% on average seems like a pretty minimal difference.

**Comment by shorowit** [comment]
Hmm, what is the possible explanation for why things are off by 2-5%? If the distribution has a mean of 1.0 and we have enough samples, it seems like we should be closer.

Would it make sense to do a quick run where we only use the 100% Usage option and see if that matches better? That could help isolate whether the discrepancy is caused by the energy model or the distribution.

**Comment by jmaguire1** [comment]
@shorowit: The mean of the % distributions is also 1.02, so I'm pretty confident if we use all 100% multipliers we'll get 1.00 exactly. It seems like this is either not enough samples (unlikely) or the distribution is just slightly off when we generated them. I can look at tweaking the bin weights to get this to average exactly 1.00 if we think it's worth the effort. I can tweak the distributions and we can do another 30k run if we think that's worth doing.

**Comment by afontani** [comment]
@jmaguire1 : to double-check the shifting of the distribution to make sure it was done correctly and correspond to the ~2% discrepancy.

**Comment by jmaguire1** [comment]
So now that this is fixed in resstock-estimation (see https://github.com/NREL/resstock-estimation/pull/420) and tested with a 30k sample, I think this is good?

Here's what I get on my sample for an average multiplier so this is documented in the PR:
image

**Pull request merged**
