### PR TITLE
Assign above-grade height for apartment units

### LINKED ISSUE #1303: Assign above-grade height for apartment units
> > > * Add `geometry_unit_height_above_grade=auto` under Geometry Building Type RECS in options_lookup
> > 
> > 
> > You might consider setting a value in ResStockArguments for apartment units based on the type/size of MF building and where the unit is located (lower, middle, or upper story).
> 
> Probably more straightfoward for upper vs middle story (where there could be multiple middle stories)?

First step might be to try different heights (e.g., 0, 8, ..., 24) to understand how much impact this has. Then could think about using average values for different building heights.

_Originally posted by @joseph-robertson in https://github.com/NREL/resstock/issues/1298#issuecomment-2338907535_

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

Closes #1303.

Proposal:
* MF:
  * Top: `(n_floors - 1) * ceiling_height`
  * Middle: `(n_floors - 1) / 2 * ceiling_height`
* All other combinations of building type and level set the height to "auto"; this ensures we use OS-HPXML defaults:
  * Slab: 0 ft
  * Ambient: 2 ft
  * Heated Basement: -7 ft
  * Unheated Basement: 0 ft
  * Vented Crawlspace: 0 ft
  * Unvented Crawlspace: 0 ft

Update BuildExistingModel to register unit height above grade as `build_existing_model.unit_height_above_grade`.

**Fuel Use: Electricity: Total**
image
**Fuel Use: Natural Gas: Total**
image
**HVAC Design Load: Heating: Total**
image
**HVAC Design Load: Cooling Latent: Total**
image
**HVAC Design Load: Cooling Sensible: Total**
image

## Checklist

Not all may apply:

- [ ] ~Tests (and test files) have been updated~
- [x] Documentation has been updated
  - [ ] ~If related to resstock-estimation, checklist includes [data dictionary](https://github.com/NREL/resstock/tree/develop/resources/data/dictionary), [source report](https://github.com/NREL/resstock/tree/develop/project_national/resources/source_report.csv), [options saturation](https://github.com/NREL/resstock/tree/develop/project_national/resources/options_saturations.csv), [options_lookup](https://github.com/NREL/resstock/blob/develop/resources/options_lookup.tsv).~
- [x] Add to the [changelog_dev.rst file](https://github.com/NREL/resstock/tree/develop/docs/read_the_docs/source/changelog/changelog_dev.rst)
- [x] `openstudio tasks.rb update_measures` has been run
- [ ] No unexpected regression test changes on CI (checked comparison artifacts)

### CODE REVIEW

**Comment by joseph-robertson** [comment]
Building ID = 10 (Geometry Stories = 21).
`geometry_unit_height_above_grade` = 0, 8, ..., 152, 160.

image
image
image

**Comment by joseph-robertson** [comment]
> It might be a minor impact, but I'd suggest defaulting to a 2ft belly for mobile homes. That's what OS-HPXML does (see [here](https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#hpxml-building-construction)).

Hmm maybe we were already defaulting to the 2 ft for Mobile Home w/ Ambient foundation type?

**Comment by afontani** [comment]
After talking a bit with @joseph-robertson, my initial reaction is that the heating energy (natural gas) goes up large enough that I might suggest we assign some value to the argument based on height. I am a little hesitant is that our modeling of large MF buildings is sort of limited right now.

**Comment by afontani** [comment]
@asparke2 : I wanted to let you know that we are considering using a new capability in OS-HPXML for multi-family units that are located above ground level. This would allow us to assign a height of the unit that impacts windspeed and resulting load due to infiltration. This is just to inform you of Multi-Family-related things coming down the pipeline as we plan the Multi-Family work.

**Comment by joseph-robertson** [comment]
What about the space (height) between floors? We should look at what OS-HPXML does, and whether we should consider, e.g., plenums, etc.

**Comment by afontani** [comment]
@joseph-robertson : The differences are relatively small and have diminishing returns as the height increases. Let's not include the distance between floors.

**Review by afontani — APPROVED** [review]
If the tests pass, let's merge this.

**Pull request merged**
