### PR TITLE
Update to 2022 Cambium release

### LINKED ISSUE #1033: Update to 2022 Cambium release
Resstock and Comstock are using 2021 Cambium data.
https://github.com/NREL/resstock/tree/develop/resources/data/cambium

Cambium 2022 data is out.  This issue is to update to the 2022 data.

### LINKED ISSUE #1063: Cambium start year harmonization
Can we add the 2025 Start numbers we used for EUSS Residential Round 1 to the /develop branch (Cambium 2021) and also add 2025 Start numbers from Cambium 2022? Any analysis that wants to use the same numbers as EUSS Residential Round 1 will want the former, and I don't think we should be using historical start years in general. 

https://github.com/NREL/resstock/tree/run/euss/resources/data/cambium

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

Closes #1033.
Closes #1063.

Checklist:
- [x] Move all existing files from `resources/data/cambium` to `resources/data/cambium/2021`
       Create a new folder `resources/data/cambium/2022`

- [x] Create "Cambium_2022_Select_For_ResStock.xlsx" by pulling data according to the README, populating spreadsheet tabs accordingly.

  @ekpresent Did you originally do this by hand? It's easy copy-paste for LRMER, but appears that AER would be much more annoying. Update: I scripted the generation of AER data files.

- [x] @mdahlhausen @ekpresent Decide on incorporating any new scenarios.

  Year | LRMER | AER
  -- | -- | --
  2021, 2022 | Mid-case | Mid-case
  2021, 2022 | Low RE Costs | Low renewable energy cost
  2021, 2022 | High RE Costs | High renewable energy cost
  2022 | Low NG Prices | Low natural gas prices
  2022 | High NG Prices | High natural gas prices
  2022 | Electrification | High electrification
  2021, 2022 | 95% Decarb by 2050 | Mid-case with 95% decarbonization by 2050
  2021, 2022 | 95% Decarb by 2035 | Mid-case with 100% decarbonization by 2035
  2022 | Mid-case (credits expire) | Mid-case with tax credit expiration
  2022 | Low RE Costs (credits expire) | Low renewable energy cost with tax credit expiration

  @mdahlhausen Do I have this mapped correctly? (Notice the "decarb" differences.)

- [x] Run "process_cambium_LRMER.py" on "Cambium_2022_Select_For_ResStock.xlsx" to create `resources/data/cambium/2022/LRMER_foo` folders.

- [x] Run "process_cambium_AER.py" on downloaded "hourly_gea.zip" files to create `resources/data/cambium/2022/AER_foo` folders

- [ ] Double-check `resources/data/cambium/2022/README.md`, especially the static variables.

image

## Checklist

Not all may apply:

- [x] Tests (and test files) have been updated
- [x] Documentation has been updated
- [x] Changelog has been updated
- [x] `openstudio tasks.rb update_measures` has been run
- [x] No unexpected regression test changes on CI (checked comparison artifacts)

### CODE REVIEW

**Comment by mdahlhausen** [comment]
Thanks @joseph-robertson! This looks great for me for ComStock purposes.

**Comment by afontani** [comment]
May suggest pulling in the updated data to look at differences with the project_national and project_testing models.

**Comment by shorowit** [comment]
Perhaps it's too late (?), but I recall that there's now a cambium API and sample python script that can be used to automate the retrieval of cambium data.

**Comment by shorowit** [comment]
Found the script: https://github.nrel.gov/pgagnon/scenario_viewer_api/blob/main/APIexamples.py

**Comment by ekpresent** [comment]
@joseph-robertson  yes, I made it by hand originally and did a reasonably thorough check but there could be mistakes. I do recall AER being rather annoying.

**Comment by ekpresent** [comment]
I checked in with Pieter briefly and his first instinct was that we should just make all 10 scenarios available. He also pointed me to updated scenario descriptions in the 2022 workbooks. I can continue the conversation when I am back from PTO.

**Comment by joseph-robertson** [comment]
I sent an email to James asking about a "Cambium API" (so as to hopefully make scenario data collection more automatic). Awaiting response...

**Comment by joseph-robertson** [comment]
> May suggest pulling in the updated data to look at differences with the project_national and project_testing models.

See graphic above in the description box. It shows what happens when I switch to the 2022 data (note the changes, however, in static variables).

**Review by ekpresent — APPROVED** [review]
@joseph-robertson walked me through this on 6/6/23, no reason to delay merge.

**Pull request merged**
