### PR TITLE
Add arguments for MSHP capacity retention

### PR DESCRIPTION
**Pull request by ejhw**
## Pull Request Description

Addresses part of https://github.com/NREL/OpenStudio-HPXML/issues/1011 

## Checklist

Not all may apply:

- [ ] Tests (and test files) have been updated
- [ ] Documentation has been updated
- [ ] Changelog has been updated
- [ ] `openstudio tasks.rb update_measures` has been run
- [ ] No unexpected integration/regression test changes

### CODE REVIEW

**Comment by joseph-robertson** [comment]
@shorowit What do we want to do here? Make these exact changes upstream in the OS-HPXML repo? Expose `cap_retention_frac` and `cap_retention_temp` as inputs to BuildResHPXML?

**Comment by shorowit** [comment]
> Make these exact changes upstream in the OS-HPXML repo?

We definitely don't want to do that. This implements logic specific to HP options that the ResStock team is trying to evaluate.

> Expose `cap_retention_frac` and `cap_retention_temp` as inputs to BuildResHPXML?

I don't love this as it'd be confusing to explain why these inputs are available for MSHPs and not ASHPs, but I realize we're between a rock and a hard place here. @ejhw Do you not care about cold climate central ASHPs?

**Comment by shorowit** [comment]
I suppose one could specify a cold climate ducted MSHP instead of a cold climate central ASHP to take advantage of these inputs for ducted systems.

**Comment by ejhw** [comment]
Yes, in fact we are planning to do that for upcoming ABC runs that use a pre-hpxml branch, since we don’t have the necessary COP arguments for a 13 HSPF ASHP

—
Eric Wilson, PE
Senior Research Engineer | Buildings Technologies and Science Center

National Renewable Energy Laboratory (NREL)
15013 Denver West Parkway | Golden, CO 80401
303.275.4676 | M: 720.607.9575
***@***.***
Pronouns: he/him/his
________________________________

**Comment by ejhw** [comment]
Though even 10 HSPF varspeed units can have good capacity retention so yes it is a concern generally.

—
Eric Wilson, PE
Senior Research Engineer | Buildings Technologies and Science Center

National Renewable Energy Laboratory (NREL)
15013 Denver West Parkway | Golden, CO 80401
303.275.4676 | M: 720.607.9575
***@***.***
Pronouns: he/him/his
________________________________

**Comment by joseph-robertson** [comment]
Options:
- (1) Branch off of OS-HPXML and expose the two inputs (would require that users pull in the correct branch into ResStock)
- (2) Same exact thing but directly implemented into the subtree (might run into subtree pull conflicts)

**Comment by joseph-robertson** [comment]
@shorowit Is the idea behind exposing these two MSHP arguments (only in the subtree) just for convenience? (Why not just accept this PR as-is?)

**Comment by shorowit** [comment]
So that each HP option in options_lookup.tsv can have individual values set, as was the case in pre-HPXML days.

**Comment by joseph-robertson** [comment]
@shorowit Each _minisplit_ HP, correct? Appears that the old lookup only had two sets of frac/temp values: 0.25/-5 and 0.5/-15. This PR re-introduces them to the lookup (although the previous approach of having the if block hard-set would've worked, too).

**Comment by shorowit** [comment]
Yes, it only applies to mini-split HPs.

**Comment by joseph-robertson** [comment]
@ejhw I was waiting for @whiphi92's testing/review, but yes I think it's ready.

**Comment by whiphi92** [comment]
> @ejhw I was waiting for @whiphi92's testing/review, but yes I think it's ready.

Apologies, I had tested this a few weeks ago and it seemed good to go.

**Review by joseph-robertson — APPROVED** [review]

**Pull request merged**
