### PR TITLE
Pin ubuntu runner version in CI for stability

### PR DESCRIPTION
**Pull request by rajeee**
## Pull Request Description
Our CI is failing due to ubunut-latest being recently updated to Ubuntu 24.04.  This PR pins ubuntu version to 22.04 - a version that has been working for us so far.

### Related Pull Requests
[related PRs from different repositories]

### Related Issues
CI is failing when trying to install buildstockbatch on system python. 
Error:
```
Run pip install git+https://github.com/NREL/buildstockbatch.git@develop
  pip install git+https://github.com/NREL/buildstockbatch.git@develop
  
  buildstock_local project_national/national_baseline.yml
  buildstock_local project_testing/testing_baseline.yml
  
  buildstock_local project_national/national_upgrades.yml
  buildstock_local project_testing/testing_upgrades.yml
  shell: /usr/bin/bash -e {0}
  env:
    OPENSTUDIO_VER: 3.8.0
    OPENSTUDIO_SHA: f953b6fcaf
    OPENSTUDIO_PLATFORM: Ubuntu-[2](https://github.com/NREL/resstock/actions/runs/11335475928/job/31524166324?pr=929#step:5:2)0.04-x86_64
    OPENSTUDIO_EXT: deb
    OPENSTUDIO_URL: https://github.com/NREL/OpenStudio/releases/download/v[3](https://github.com/NREL/resstock/actions/runs/11335475928/job/31524166324?pr=929#step:5:3).8.0
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP [6](https://github.com/NREL/resstock/actions/runs/11335475928/job/31524166324?pr=929#step:5:6)68 for the detailed specification.
Error: Process completed with exit code 1.
```

#### Required:
- [ ] [Technical reference documentation](https://github.com/NREL/resstock/tree/develop/docs/read_the_docs) has been updated
- [ ] Add to the [changelog_dev.rst file](https://github.com/NREL/resstock/tree/develop/docs/read_the_docs/source/changelog/changelog_dev.rst)
- [ ] No unexpected regression test changes on CI (comparison artifacts have been checked)

#### Optional (not all items may apply):
- [ ] Tests (and test files) have been updated
- [ ] Supporting resource files have been updated (related to resstock-estimation)
  - [ ] [data dictionary](https://github.com/NREL/resstock/tree/develop/resources/data/dictionary)
  - [ ] [source report](https://github.com/NREL/resstock/tree/develop/project_national/resources/source_report.csv)
  - [ ] [options saturation](https://github.com/NREL/resstock/tree/develop/project_national/resources/options_saturations.csv)
  - [ ] [options_lookup](https://github.com/NREL/resstock/blob/develop/resources/options_lookup.tsv)
- [ ] `openstudio tasks.rb update_measures` has been run

### CODE REVIEW

**Review by afontani — APPROVED** [review]
This is fine for now to make sure development can continue for everyone else. We need to figure out why our workflow is broken on ubuntu 24.04. Maybe it won't matter with some upcoming CI changes.

**Comment by rajeee** [comment]
I think ubuntu 24.04 runner comes with more python packages and that conflicts with the packages we are trying to install. This could be resolved by using containers or virtual environment. Or, if we migrate to different CI environment with different runners, this is no longer relevant.

**Comment by joseph-robertson** [comment]
FYI, [this](https://github.com/NREL/OpenStudio-HPXML/commit/09c7cd1860d674b8bfb7f3a1e716f8efbde4fb9f) is the approach that OS-HPXML took to get around this issue.

Based on the "comes with more python packages" comment above, could we also try _not_ pip installing?

**Comment by shorowit** [comment]
FYI, GitHub just reverted ubuntu-latest to 22.04 because it broke so many things. So it looks like @rajeee's solution was smart and avoids the ping-ponging that is currently going on.

**Pull request merged**
