### PR TITLE
Rename changes, try 2

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

Renames all "OpenStudio-BuildStock" (case insensitive; only references to the repo) to "resstock".

## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [ ] All rake tasks have been run, and pass
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [ ] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [ ] All tests are passing (green) on circleci
- [ ] The [changelog](https://github.com/NREL/OpenStudio-BuildStock/blob/master/CHANGELOG.md) has been updated appropriately
- [ ] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Review by ejhw — APPROVED** [review]
👍

**Comment by shorowit** [comment]
Don't forget to update the "About" block on https://github.com/NREL/resstock

**Comment by joseph-robertson** [comment]
To "Modeling the existing residential building stock using OpenStudio/EnergyPlus."?

**Comment by ejhw** [comment]
Thanks @shorowit . I updated it. cc @joseph-robertson .

**Comment by ejhw** [comment]
It looks like README.md still needs to be updated though.

**Pull request merged**
